# Site settings
title: FusionInventory
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  FusionInventory website with documentation and new on this wonderfull
  inventory and software deployment tool.
baseurl: "/website" # the subpath of your site, e.g. /blog/
url: "http://fusioninventory.github.io/website" # the base hostname & protocol for your site
twitter_username: fusioninventory
github_username:  fusioninventory


paginate: 8
paginate_path: "/news/page:num/"

# Build settings
markdown: kramdown

